server:
  port: 8083

camunda.bpm:
  webapp:
    index-redirect-enabled: true
  admin-user:
    id: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka